### ISSUE TITLE
Date is missing from DESCRIPTION

### ISSUE THREAD

**Issue by RaymondBalise** [tgerke/ggconsort#16]
I would like to add a citation for your package in a paper I am submitting but `knitr::write_bib` is not working properly with your package.  

When I check the citation with  `utils::citation("ggconsort")`

I get:

```
Warning message:
In utils::citation("ggconsort") :
  no date field in DESCRIPTION file of package ‘ggconsort’
```

Can you please tweak your DESCRIPTION to include a line like:
```
Date: 2021-09-06
```
until the latest built is on CRAN.

**Comment by tgerke** [comment]
Some interesting commentary from experts I trust on this practice 😊 Likely to hold off on manually adding date until CRAN submission, which I am aiming for as soon as some of the supporting documentation is rounded out (i.e. very soon!). I do want to say I appreciate you citing packages like this: you are awesome!
https://github.com/r-lib/usethis/issues/806
> We are, in general, anti-Date field because it is automatically added when, say, CRAN builds your package and that Date will always be correct, by definition. So it turns out that manually tending a Date field causes more problems than it solves, because people routinely forget to update it.

**Comment by RaymondBalise** [comment]
Nod. I totally agree that once a package hits GitHub having the date makes no sense.   My workflow is to include the date on release candidates (version 0.0.0.900X) until I get a version on CRAN.  After that I kill it.  I cloned the package and added the date for the paper.  Who knows, one of these centuries, promotion and tenure committees may find a way to quantify the impact of our work. Until then citations have to help….

Ray
