### ISSUE TITLE
Edit font family

### ISSUE THREAD

**Issue by csthiago** [tgerke/ggconsort#17]
Hi.

Nice work!
I have looked around, but I couldn't find how to edit the font family. What element should I edit?

Thanks!

**Comment by ccsarapas** [comment]
@csthiago You can pass `family` to `geom_consort()`. e.g.,:
```
study_consort %>%
  ggplot() + 
  geom_consort(family = "Segoe UI")
  ```
`geom_consort()` ultimately passes arguments to the `aes()` call within [`ggtext::geom_richtext()`](https://wilkelab.org/ggtext/reference/geom_richtext.html). NB, I don't think this is an officially supported feature.

**Comment by csthiago** [comment]
Thanks @ccsarapas
